logging:
 config: config/logback.xml
 level.*: debug

zookeeper:
 connects: 192.168.3.31:2181
 marsRoot: jjg

cluster:
 type: GM
 name: GM_SHIYI
 weight: 2

spring:
 main:
  web-application-type: none
 data:
  redis:
   host: 192.168.3.31
   port: 6379
   database: 11
  mongodb:
   uri: mongodb://admin:jjg123456@192.168.3.31:27017/jjg_game_dev