logging:
 config: config/logback.xml
 level.*: debug

zookeeper:
 connects: 192.168.3.31:2181
 marsRoot: jjg

cluster:
 type: GAME
 name: GAME_POKER_SHIYI
 gm: true
 gameTypes: []
 tcpAddress:
  port: 13007
  host: 192.168.3.46

spring:
 main:
  web-application-type: none
 data:
  redis:
   host: 192.168.3.31
   port: 6379
   password: 123456
   database: 11
  mongodb:
   uri: mongodb://admin:jjg123456@192.168.3.31:27017/jjg_game_dev?authSource=admin
 kafka:
  bootstrap-servers: 192.168.3.31:9092
  producer:
   key-serializer: org.apache.kafka.common.serialization.StringSerializer
   value-serializer: org.apache.kafka.common.serialization.StringSerializer
   acks: all
   enable-idempotence: true
   retries: 3
   batch-size: 16384
   compression-type: gzip
   max-request-size: 1048576
   linger-ms: 50