logging:
 config: config/logback.xml
 level.*: debug

zookeeper:
 connects: 192.168.3.31:2181
 marsRoot: jjg

dubbo:
 application:
  name: logserver
 registry:
  address: zookeeper://${zookeeper.connects}
  register-mode: instance
 scan:
  base-packages: com.vegasnight.game
 protocol:
   name: dubbo
   host: 192.168.3.31
   port: 20883


spring:
 main:
  web-application-type: none