logging:
 config: config/logback.xml
 level.*: debug

zookeeper:
 connects: 192.168.3.31:2181
 marsRoot: jjg

cluster:
 type: GATE
 name: GT_SHIYI
 weight: 2
 tcpAddress:
  port: 13005
  host: 192.168.3.46

spring:
  main:
   web-application-type: none

gate:
  wsAddress:
   port: 9001
   host: 0.0.0.0

